spring.application.name=mos_backend

# DataSource (H2 in-memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Spring Security default user
spring.security.user.name=user
spring.security.user.password=password

# Spring Session JDBC schema initialization
spring.session.jdbc.initialize-schema=always
